server:
  port: 8080
  contextPath: /im
mysql:
  ip: 106.14.18.18
  port: 3306
  database: im
  params: charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: pass1234
jwt:
  secret: lghlmcl
  expirationTime: 10800