server:
  port: 8080
  contextPath: /im
mysql:
  ip: 106.14.18.18
  port: 3306
  database: im
  params: charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: pass1234
redis:
  ip: 106.14.18.18
  port: 6379
  password: pass1234
  DB: 0
jwt:
  secret: lghlmcl
  expirationTime: 10800
third:
  aliyun:
    appCode: c09d6e05b220456a98633777f423a800
    phoneAttributionUrl: https://jshmgsdmfb.market.alicloudapi.com/shouji/query
    ipAttributionUrl: https://qryip.market.alicloudapi.com/lundear/qryip
    phoneSendVerifyCodeUrl: https://dfsns.market.alicloudapi.com/data/send_sms
    phoneSendVerifyCodeTemplateId: TPL_0001
    phoneVerifyCodeExpireMin: 5
email:
  fromAccount: ycq <903421928@qq.com>
  emailServerAddr: smtp.qq.com:25
  host: smtp.qq.com
  username: 903421928@qq.com
  authorizationCode: jrwfxdmbzphzbcgj
  emailVerifyCodeExpireMin: 5
regexp:
  phone: ^1(3[0-9]|4[01456879]|5[0-35-9]|6[2567]|7[0-8]|8[0-9]|9[0-35-9])\d{8}$
  email: ^([a-zA-Z\d][\w-]{2,})@(\w{2,})\.([a-z]{2,})(\.[a-z]{2,})?$